### ISSUE TITLE
[BUG] - Prefabs added from the object list always stay at coordinates 0, 0, 0

### ISSUE THREAD

**Issue by Cliffworms** [KABoissonneault/DFU-LocationLoader#15]
When you add a prefab as a new object and place it somewhere, the new coordinates are not registered when you save the prefab and load it again. 

To reproduce : 

- Create a new prefab
- Import a prefab of your choice as a new object and place it somewhere else than 0, 0, 0
- Save and reload. The prefab you placed will have returned to 0, 0, 0.

**Comment by KABoissonneault** [comment]
Fixed in 1616dbb68c4647f636cd64ac802782cd724fa0e8

It's possible it's only fixed in the editor but it's still an issue in-game. Please confirm
