### ISSUE TITLE
Rotating a prefab in the CSV does not change editor markers' position

### ISSUE THREAD

**Issue by Cliffworms** [KABoissonneault/DFU-LocationLoader#16]
I tested this with the Ladder Up/Down markers. When I rotated the prefab in the CSV file, the ladder up marker seems to have not moved, making the PC teleport in the air where the prefab is normally located when it's not rotated. 

To test, you can use the border towers files I submitted as a PR and this save game attached to one such problematic prefab.
[SAVE16.zip](https://github.com/KABoissonneault/DFU-LocationLoader/files/7954002/SAVE16.zip)

**Comment by KABoissonneault** [comment]
Ladders should be fixed in 6974c777c4e3e14c88400d4f4924e2d7d088c9c7

I don't think the other markers have issues, but tell me if they do
