### ISSUE TITLE
Request : Add mod dependencies for custom objects

### ISSUE THREAD

**Issue by Cliffworms** [KABoissonneault/DFU-LocationLoader#17]
With Ninelan's Expanded Textures upcoming release, which will be a .dfmod, it'd be very useful to be able to load it up in the Prefab Editor so we could use the mod's custom objects in our prefabs. Like regional banners and farm animals.

Merci bien!

**Comment by KABoissonneault** [comment]
Fixed in 2d4406c255337e7741a1ae9aa02e430618309eff
