### ISSUE TITLE
Request : Move objects by 0.025 units instead of freeform

### ISSUE THREAD

**Issue by Cliffworms** [KABoissonneault/DFU-LocationLoader#19]
Currently, moving models and billboards is freeform. Sometimes it can move by 0.01, others by 0.08. It would be beneficial for the construction of custom buildings to have the same settings as the world data editor, where objects are moved by 0.025 units.

Thanks!

**Comment by KABoissonneault** [comment]
Implemented in 0a1269c6096d3f77bff3a2cce32f9d72322dd557
